### ISSUE TITLE
Not all control paths return value

### ISSUE THREAD

**Issue by Eddie-cz** [mzimbres/aedis#12] opened 2022-06-27 20:10 UTC
aeedis\impl\error.ipp(47): error C4715: 'aedis::detail::error_category_impl::message': not all control paths return a value
clang 14.0.6

**Comment by mzimbres** [comment] 2022-07-02 21:52
Thanks for reporting. I can't reproduce this on the master branch. Notice the high-level Aedis API was redesigned and the problem may have already been fixed.

**Comment by Eddie-cz** [comment] 2022-07-02 21:56
error.ipp, std::string message(int ev) fnc
- clearly not returning value on case default, assert is not enough

**Comment by mzimbres** [comment] 2022-07-03 06:17
Fixed in the master. Thanks for reporting.

**Closed by mzimbres** 2022-07-03 06:17 UTC
